// Geography data structure
export interface SubRegion {
  name: string
  id: string
}

export interface Region {
  name: string
  id: string
  subRegions?: SubRegion[]
}

export interface Continent {
  name: string
  id: string
  regions: Region[]
}

export interface GeoData {
  continents: Continent[]
}

// Function to fetch geographical data
export async function getGeoData(): Promise<GeoData> {
  // In a real application, this would be an API call
  // For now, we'll return the static data
  return {
    continents: [
      {
        name: "Africa",
        id: "africa",
        regions: [
          {
            name: "Algeria",
            id: "algeria",
            subRegions: [
              { name: "Adrar", id: "adrar" },
              { name: "Alger", id: "alger" },
              { name: "Annaba", id: "annaba" },
              { name: "Aïn Defla", id: "ain-defla" },
              { name: "Aïn Témouchent", id: "ain-temouchent" },
              { name: "Batna", id: "batna" },
              { name: "Biskra", id: "biskra" },
              { name: "Blida", id: "blida" },
              { name: "Bordj Bou Arréridj", id: "bordj-bou-arreridj" },
              { name: "Bouira", id: "bouira" },
              { name: "Boumerdès", id: "boumerdes" },
              { name: "Béchar", id: "bechar" },
              { name: "Béjaïa", id: "bejaia" },
              { name: "Chlef", id: "chlef" },
              { name: "Constantine", id: "constantine" },
              { name: "Djelfa", id: "djelfa" },
              { name: "El Bayadh", id: "el-bayadh" },
              { name: "El Oued", id: "el-oued" },
              { name: "El Tarf", id: "el-tarf" },
              { name: "Ghardaïa", id: "ghardaia" },
              { name: "Guelma", id: "guelma" },
              { name: "Illizi", id: "illizi" },
              { name: "Jijel", id: "jijel" },
              { name: "Khenchela", id: "khenchela" },
              { name: "Laghouat", id: "laghouat" },
              { name: "Mascara", id: "mascara" },
              { name: "Mila", id: "mila" },
              { name: "Mostaganem", id: "mostaganem" },
              { name: "Msila", id: "msila" },
              { name: "Médéa", id: "medea" },
              { name: "Naama", id: "naama" },
              { name: "Oran", id: "oran" },
              { name: "Ouargla", id: "ouargla" },
              { name: "Oum el Bouaghi", id: "oum-el-bouaghi" },
              { name: "Relizane", id: "relizane" },
              { name: "Saïda", id: "saida" },
              { name: "Sidi Bel Abbès", id: "sidi-bel-abbes" },
              { name: "Skikda", id: "skikda" },
              { name: "Souk Ahras", id: "souk-ahras" },
              { name: "Sétif", id: "setif" },
              { name: "Tamanghasset", id: "tamanghasset" },
              { name: "Tiaret", id: "tiaret" },
              { name: "Tindouf", id: "tindouf" },
              { name: "Tipaza", id: "tipaza" },
              { name: "Tissemsilt", id: "tissemsilt" },
              { name: "Tizi Ouzou", id: "tizi-ouzou" },
              { name: "Tlemcen", id: "tlemcen" },
              { name: "Tébessa", id: "tebessa" },
            ],
          },
          {
            name: "Angola",
            id: "angola",
            subRegions: [
              { name: "Bengo", id: "bengo" },
              { name: "Benguela", id: "benguela" },
              { name: "Bié", id: "bie" },
              { name: "Cabinda", id: "cabinda" },
              { name: "Cuando-Cubango", id: "cuando-cubango" },
              { name: "Cuanza Norte", id: "cuanza-norte" },
              { name: "Cuanza Sul", id: "cuanza-sul" },
              { name: "Cunene", id: "cunene" },
              { name: "Huambo", id: "huambo" },
              { name: "Huíla", id: "huila" },
              { name: "Luanda", id: "luanda" },
              { name: "Lunda Norte", id: "lunda-norte" },
              { name: "Lunda Sul", id: "lunda-sul" },
              { name: "Malange", id: "malange" },
              { name: "Moxico", id: "moxico" },
              { name: "Namibe", id: "namibe" },
              { name: "Uíge", id: "uige" },
              { name: "Zaire", id: "zaire" },
            ],
          },
          {
            name: "Benin",
            id: "benin",
            subRegions: [
              { name: "Alibori", id: "alibori" },
              { name: "Atakora", id: "atakora" },
              { name: "Atlantique", id: "atlantique" },
              { name: "Borgou", id: "borgou" },
              { name: "Collines", id: "collines" },
              { name: "Donga", id: "donga" },
              { name: "Kouffo", id: "kouffo" },
              { name: "Littoral", id: "littoral" },
              { name: "Mono", id: "mono" },
              { name: "Ouémé", id: "oueme" },
              { name: "Plateau", id: "plateau" },
              { name: "Zou", id: "zou" },
            ],
          },
          {
            name: "Botswana",
            id: "botswana",
            subRegions: [
              { name: "Central", id: "central" },
              { name: "Ghanzi", id: "ghanzi" },
              { name: "Kgalagadi", id: "kgalagadi" },
              { name: "Kgatleng", id: "kgatleng" },
              { name: "Kweneng", id: "kweneng" },
              { name: "North-East", id: "north-east" },
              { name: "North-West", id: "north-west" },
              { name: "South-East", id: "south-east" },
              { name: "Southern", id: "southern" },
            ],
          },
          { name: "Burkina Faso", id: "burkina-faso" },
          { name: "Burundi", id: "burundi" },
          { name: "Cabo Verde", id: "cabo-verde" },
          { name: "Cameroon", id: "cameroon" },
          { name: "Central African Republic", id: "central-african-republic" },
          { name: "Chad", id: "chad" },
          { name: "Comoros", id: "comoros" },
          { name: "Congo", id: "congo" },
          { name: "Congo, Democratic Republic of the", id: "congo-democratic-republic" },
          { name: "Cote d'Ivoire", id: "cote-divoire" },
          { name: "Djibouti", id: "djibouti" },
          { name: "Egypt", id: "egypt" },
          { name: "Equatorial Guinea", id: "equatorial-guinea" },
          { name: "Eritrea", id: "eritrea" },
          { name: "Eswatini", id: "eswatini" },
          { name: "Ethiopia", id: "ethiopia" },
          { name: "Gabon", id: "gabon" },
          { name: "Gambia", id: "gambia" },
          { name: "Ghana", id: "ghana" },
          { name: "Guinea", id: "guinea" },
          { name: "Guinea-Bissau", id: "guinea-bissau" },
          { name: "Kenya", id: "kenya" },
          { name: "Lesotho", id: "lesotho" },
          { name: "Liberia", id: "liberia" },
          { name: "Libya", id: "libya" },
          { name: "Madagascar", id: "madagascar" },
          { name: "Malawi", id: "malawi" },
          { name: "Mali", id: "mali" },
          { name: "Mauritania", id: "mauritania" },
          { name: "Mauritius", id: "mauritius" },
          { name: "Morocco", id: "morocco" },
          { name: "Mozambique", id: "mozambique" },
          { name: "Namibia", id: "namibia" },
          { name: "Niger", id: "niger" },
          { name: "Nigeria", id: "nigeria" },
          { name: "Rwanda", id: "rwanda" },
          { name: "Sao Tome and Principe", id: "sao-tome-and-principe" },
          { name: "Senegal", id: "senegal" },
          { name: "Seychelles", id: "seychelles" },
          { name: "Sierra Leone", id: "sierra-leone" },
          { name: "Somalia", id: "somalia" },
          { name: "South Africa", id: "south-africa" },
          { name: "South Sudan", id: "south-sudan" },
          { name: "Sudan", id: "sudan" },
          { name: "Tanzania", id: "tanzania" },
          { name: "Togo", id: "togo" },
          { name: "Tunisia", id: "tunisia" },
          { name: "Uganda", id: "uganda" },
          { name: "Zambia", id: "zambia" },
          { name: "Zimbabwe", id: "zimbabwe" },
        ],
      },
      {
        name: "Asia",
        id: "asia",
        regions: [
          {
            name: "Afghanistan",
            id: "afghanistan",
            subRegions: [
              { name: "Badakhshān", id: "badakhshan" },
              { name: "Baghlān", id: "baghlan" },
              { name: "Balkh", id: "balkh" },
              { name: "Bādghīs", id: "badghis" },
              { name: "Bāmyān", id: "bamyan" },
              { name: "Dāykundī", id: "daykundi" },
              { name: "Farāh", id: "farah" },
              { name: "Fāryāb", id: "faryab" },
              { name: "Ghaznī", id: "ghazni" },
              { name: "Ghōr", id: "ghor" },
              { name: "Helmand", id: "helmand" },
              { name: "Herāt", id: "herat" },
              { name: "Jowzjān", id: "jowzjan" },
              { name: "Kandahār", id: "kandahar" },
              { name: "Khōst", id: "khost" },
              { name: "Kunar", id: "kunar" },
              { name: "Kunduz", id: "kunduz" },
              { name: "Kābul", id: "kabul" },
              { name: "Kāpīsā", id: "kapisa" },
              { name: "Laghmān", id: "laghman" },
              { name: "Lōgar", id: "logar" },
              { name: "Nangarhār", id: "nangarhar" },
              { name: "Nīmrōz", id: "nimroz" },
              { name: "Nūristān", id: "nuristan" },
              { name: "Paktiyā", id: "paktiya" },
              { name: "Paktīkā", id: "paktika" },
              { name: "Panjshayr", id: "panjshayr" },
              { name: "Parwān", id: "parwan" },
              { name: "Samangān", id: "samangan" },
              { name: "Sar-e Pul", id: "sar-e-pul" },
              { name: "Takhār", id: "takhar" },
              { name: "Uruzgān", id: "uruzgan" },
              { name: "Wardak", id: "wardak" },
              { name: "Zābul", id: "zabul" },
            ],
          },
          { name: "Armenia", id: "armenia" },
          { name: "Azerbaijan", id: "azerbaijan" },
          { name: "Bahrain", id: "bahrain" },
          { name: "Bangladesh", id: "bangladesh" },
          { name: "Bhutan", id: "bhutan" },
          { name: "Brunei", id: "brunei" },
          { name: "Cambodia", id: "cambodia" },
          {
            name: "China",
            id: "china",
            subRegions: [
              { name: "Anhui Sheng", id: "anhui-sheng" },
              { name: "Beijing Shi", id: "beijing-shi" },
              { name: "Chongqing Shi", id: "chongqing-shi" },
              { name: "Fujian Sheng", id: "fujian-sheng" },
              { name: "Gansu Sheng", id: "gansu-sheng" },
              { name: "Guangdong Sheng", id: "guangdong-sheng" },
              { name: "Guangxi Zhuangzu Zizhiqu", id: "guangxi-zhuangzu-zizhiqu" },
              { name: "Guizhou Sheng", id: "guizhou-sheng" },
              { name: "Hainan Sheng", id: "hainan-sheng" },
              { name: "Hebei Sheng", id: "hebei-sheng" },
              { name: "Heilongjiang Sheng", id: "heilongjiang-sheng" },
              { name: "Henan Sheng", id: "henan-sheng" },
              { name: "Hong Kong SAR", id: "hong-kong-sar" },
              { name: "Hubei Sheng", id: "hubei-sheng" },
              { name: "Hunan Sheng", id: "hunan-sheng" },
              { name: "Jiangsu Sheng", id: "jiangsu-sheng" },
              { name: "Jiangxi Sheng", id: "jiangxi-sheng" },
              { name: "Jilin Sheng", id: "jilin-sheng" },
              { name: "Liaoning Sheng", id: "liaoning-sheng" },
              { name: "Macao SAR", id: "macao-sar" },
              { name: "Nei Mongol Zizhiqu", id: "nei-mongol-zizhiqu" },
              { name: "Ningxia Huizi Zizhiqu", id: "ningxia-huizi-zizhiqu" },
              { name: "Qinghai Sheng", id: "qinghai-sheng" },
              { name: "Shaanxi Sheng", id: "shaanxi-sheng" },
              { name: "Shandong Sheng", id: "shandong-sheng" },
              { name: "Shanghai Shi", id: "shanghai-shi" },
              { name: "Shanxi Sheng", id: "shanxi-sheng" },
              { name: "Sichuan Sheng", id: "sichuan-sheng" },
              { name: "Taiwan Sheng", id: "taiwan-sheng" },
              { name: "Tianjin Shi", id: "tianjin-shi" },
              { name: "Xinjiang Uygur Zizhiqu", id: "xinjiang-uygur-zizhiqu" },
              { name: "Xizang Zizhiqu", id: "xizang-zizhiqu" },
              { name: "Yunnan Sheng", id: "yunnan-sheng" },
              { name: "Zhejiang Sheng", id: "zhejiang-sheng" },
            ],
          },
          { name: "Cyprus", id: "cyprus" },
          { name: "Georgia", id: "georgia" },
          {
            name: "India",
            id: "india",
            subRegions: [
              { name: "Andaman and Nicobar Islands", id: "andaman-and-nicobar-islands" },
              { name: "Andhra Pradesh", id: "andhra-pradesh" },
              { name: "Arunachal Pradesh", id: "arunachal-pradesh" },
              { name: "Assam", id: "assam" },
              { name: "Bihar", id: "bihar" },
              { name: "Chandigarh", id: "chandigarh" },
              { name: "Chhattisgarh", id: "chhattisgarh" },
              { name: "Dadra and Nagar Haveli", id: "dadra-and-nagar-haveli" },
              { name: "Daman and Diu", id: "daman-and-diu" },
              { name: "Delhi", id: "delhi" },
              { name: "Goa", id: "goa" },
              { name: "Gujarat", id: "gujarat" },
              { name: "Haryana", id: "haryana" },
              { name: "Himachal Pradesh", id: "himachal-pradesh" },
              { name: "Jammu and Kashmir", id: "jammu-and-kashmir" },
              { name: "Jharkhand", id: "jharkhand" },
              { name: "Karnataka", id: "karnataka" },
              { name: "Kerala", id: "kerala" },
              { name: "Lakshadweep", id: "lakshadweep" },
              { name: "Madhya Pradesh", id: "madhya-pradesh" },
              { name: "Maharashtra", id: "maharashtra" },
              { name: "Manipur", id: "manipur" },
              { name: "Meghalaya", id: "meghalaya" },
              { name: "Mizoram", id: "mizoram" },
              { name: "Nagaland", id: "nagaland" },
              { name: "Odisha", id: "odisha" },
              { name: "Puducherry", id: "puducherry" },
              { name: "Punjab", id: "punjab" },
              { name: "Rajasthan", id: "rajasthan" },
              { name: "Sikkim", id: "sikkim" },
              { name: "Tamil Nadu", id: "tamil-nadu" },
              { name: "Telangana", id: "telangana" },
              { name: "Tripura", id: "tripura" },
              { name: "Uttar Pradesh", id: "uttar-pradesh" },
              { name: "Uttarakhand", id: "uttarakhand" },
              { name: "West Bengal", id: "west-bengal" },
            ],
          },
          { name: "Indonesia", id: "indonesia" },
          { name: "Iran", id: "iran" },
          { name: "Iraq", id: "iraq" },
          { name: "Israel", id: "israel" },
          {
            name: "Japan",
            id: "japan",
            subRegions: [
              { name: "Aichi", id: "aichi" },
              { name: "Akita", id: "akita" },
              { name: "Aomori", id: "aomori" },
              { name: "Chiba", id: "chiba" },
              { name: "Ehime", id: "ehime" },
              { name: "Fukui", id: "fukui" },
              { name: "Fukuoka", id: "fukuoka" },
              { name: "Fukushima", id: "fukushima" },
              { name: "Gifu", id: "gifu" },
              { name: "Gunma", id: "gunma" },
              { name: "Hiroshima", id: "hiroshima" },
              { name: "Hokkaido", id: "hokkaido" },
              { name: "Hyogo", id: "hyogo" },
              { name: "Ibaraki", id: "ibaraki" },
              { name: "Ishikawa", id: "ishikawa" },
              { name: "Iwate", id: "iwate" },
              { name: "Kagawa", id: "kagawa" },
              { name: "Kagoshima", id: "kagoshima" },
              { name: "Kanagawa", id: "kanagawa" },
              { name: "Kochi", id: "kochi" },
              { name: "Kumamoto", id: "kumamoto" },
              { name: "Kyoto", id: "kyoto" },
              { name: "Mie", id: "mie" },
              { name: "Miyagi", id: "miyagi" },
              { name: "Miyazaki", id: "miyazaki" },
              { name: "Nagano", id: "nagano" },
              { name: "Nagasaki", id: "nagasaki" },
              { name: "Nara", id: "nara" },
              { name: "Niigata", id: "niigata" },
              { name: "Oita", id: "oita" },
              { name: "Okayama", id: "okayama" },
              { name: "Okinawa", id: "okinawa" },
              { name: "Osaka", id: "osaka" },
              { name: "Saga", id: "saga" },
              { name: "Saitama", id: "saitama" },
              { name: "Shiga", id: "shiga" },
              { name: "Shimane", id: "shimane" },
              { name: "Shizuoka", id: "shizuoka" },
              { name: "Tochigi", id: "tochigi" },
              { name: "Tokushima", id: "tokushima" },
              { name: "Tokyo", id: "tokyo" },
              { name: "Tottori", id: "tottori" },
              { name: "Toyama", id: "toyama" },
              { name: "Wakayama", id: "wakayama" },
              { name: "Yamagata", id: "yamagata" },
              { name: "Yamaguchi", id: "yamaguchi" },
              { name: "Yamanashi", id: "yamanashi" },
            ],
          },
          { name: "Jordan", id: "jordan" },
          { name: "Kazakhstan", id: "kazakhstan" },
          { name: "Korea, North", id: "korea-north" },
          { name: "Korea, South", id: "korea-south" },
          { name: "Kuwait", id: "kuwait" },
          { name: "Kyrgyzstan", id: "kyrgyzstan" },
          { name: "Laos", id: "laos" },
          { name: "Lebanon", id: "lebanon" },
          { name: "Malaysia", id: "malaysia" },
          { name: "Maldives", id: "maldives" },
          { name: "Mongolia", id: "mongolia" },
          { name: "Myanmar", id: "myanmar" },
          { name: "Nepal", id: "nepal" },
          { name: "Oman", id: "oman" },
          { name: "Pakistan", id: "pakistan" },
          { name: "Philippines", id: "philippines" },
          { name: "Qatar", id: "qatar" },
          { name: "Saudi Arabia", id: "saudi-arabia" },
          { name: "Singapore", id: "singapore" },
          { name: "Sri Lanka", id: "sri-lanka" },
          { name: "Syria", id: "syria" },
          { name: "Taiwan", id: "taiwan" },
          { name: "Tajikistan", id: "tajikistan" },
          { name: "Thailand", id: "thailand" },
          { name: "Timor-Leste", id: "timor-leste" },
          { name: "Turkey", id: "turkey" },
          { name: "Turkmenistan", id: "turkmenistan" },
          { name: "United Arab Emirates", id: "united-arab-emirates" },
          { name: "Uzbekistan", id: "uzbekistan" },
          { name: "Vietnam", id: "vietnam" },
          { name: "Yemen", id: "yemen" },
        ],
      },
      {
        name: "Europe",
        id: "europe",
        regions: [
          { name: "Albania", id: "albania" },
          { name: "Andorra", id: "andorra" },
          { name: "Austria", id: "austria" },
          { name: "Belarus", id: "belarus" },
          { name: "Belgium", id: "belgium" },
          { name: "Bosnia and Herzegovina", id: "bosnia-and-herzegovina" },
          { name: "Bulgaria", id: "bulgaria" },
          { name: "Croatia", id: "croatia" },
          { name: "Czechia", id: "czechia" },
          { name: "Denmark", id: "denmark" },
          { name: "Estonia", id: "estonia" },
          { name: "Finland", id: "finland" },
          {
            name: "France",
            id: "france",
            subRegions: [
              { name: "Auvergne-Rhône-Alpes", id: "auvergne-rhone-alpes" },
              { name: "Bourgogne-Franche-Comté", id: "bourgogne-franche-comte" },
              { name: "Brittany", id: "brittany" },
              { name: "Centre-Val de Loire", id: "centre-val-de-loire" },
              { name: "Corsica", id: "corsica" },
              { name: "Grand Est", id: "grand-est" },
              { name: "Hauts-de-France", id: "hauts-de-france" },
              { name: "Île-de-France", id: "ile-de-france" },
              { name: "Normandy", id: "normandy" },
              { name: "Nouvelle-Aquitaine", id: "nouvelle-aquitaine" },
              { name: "Occitanie", id: "occitanie" },
              { name: "Pays de la Loire", id: "pays-de-la-loire" },
              { name: "Provence-Alpes-Côte d'Azur", id: "provence-alpes-cote-dazur" },
            ],
          },
          {
            name: "Germany",
            id: "germany",
            subRegions: [
              { name: "Baden-Württemberg", id: "baden-wurttemberg" },
              { name: "Bavaria", id: "bavaria" },
              { name: "Berlin", id: "berlin" },
              { name: "Brandenburg", id: "brandenburg" },
              { name: "Bremen", id: "bremen" },
              { name: "Hamburg", id: "hamburg" },
              { name: "Hesse", id: "hesse" },
              { name: "Lower Saxony", id: "lower-saxony" },
              { name: "Mecklenburg-Vorpommern", id: "mecklenburg-vorpommern" },
              { name: "North Rhine-Westphalia", id: "north-rhine-westphalia" },
              { name: "Rhineland-Palatinate", id: "rhineland-palatinate" },
              { name: "Saarland", id: "saarland" },
              { name: "Saxony", id: "saxony" },
              { name: "Saxony-Anhalt", id: "saxony-anhalt" },
              { name: "Schleswig-Holstein", id: "schleswig-holstein" },
              { name: "Thuringia", id: "thuringia" },
            ],
          },
          { name: "Greece", id: "greece" },
          { name: "Hungary", id: "hungary" },
          { name: "Iceland", id: "iceland" },
          { name: "Ireland", id: "ireland" },
          {
            name: "Italy",
            id: "italy",
            subRegions: [
              { name: "Abruzzo", id: "abruzzo" },
              { name: "Aosta Valley", id: "aosta-valley" },
              { name: "Apulia", id: "apulia" },
              { name: "Basilicata", id: "basilicata" },
              { name: "Calabria", id: "calabria" },
              { name: "Campania", id: "campania" },
              { name: "Emilia-Romagna", id: "emilia-romagna" },
              { name: "Friuli Venezia Giulia", id: "friuli-venezia-giulia" },
              { name: "Lazio", id: "lazio" },
              { name: "Liguria", id: "liguria" },
              { name: "Lombardy", id: "lombardy" },
              { name: "Marche", id: "marche" },
              { name: "Molise", id: "molise" },
              { name: "Piedmont", id: "piedmont" },
              { name: "Sardinia", id: "sardinia" },
              { name: "Sicily", id: "sicily" },
              { name: "Trentino-South Tyrol", id: "trentino-south-tyrol" },
              { name: "Tuscany", id: "tuscany" },
              { name: "Umbria", id: "umbria" },
              { name: "Veneto", id: "veneto" },
            ],
          },
          { name: "Kosovo", id: "kosovo" },
          { name: "Latvia", id: "latvia" },
          { name: "Liechtenstein", id: "liechtenstein" },
          { name: "Lithuania", id: "lithuania" },
          { name: "Luxembourg", id: "luxembourg" },
          { name: "Malta", id: "malta" },
          { name: "Moldova", id: "moldova" },
          { name: "Monaco", id: "monaco" },
          { name: "Montenegro", id: "montenegro" },
          { name: "Netherlands", id: "netherlands" },
          { name: "North Macedonia", id: "north-macedonia" },
          { name: "Norway", id: "norway" },
          { name: "Poland", id: "poland" },
          { name: "Portugal", id: "portugal" },
          { name: "Romania", id: "romania" },
          { name: "Russia", id: "russia" },
          { name: "San Marino", id: "san-marino" },
          { name: "Serbia", id: "serbia" },
          { name: "Slovakia", id: "slovakia" },
          { name: "Slovenia", id: "slovenia" },
          { name: "Spain", id: "spain" },
          { name: "Sweden", id: "sweden" },
          { name: "Switzerland", id: "switzerland" },
          { name: "Ukraine", id: "ukraine" },
          {
            name: "United Kingdom",
            id: "uk",
            subRegions: [
              { name: "England", id: "england" },
              { name: "Northern Ireland", id: "northern-ireland" },
              { name: "Scotland", id: "scotland" },
              { name: "Wales", id: "wales" },
            ],
          },
          { name: "Vatican City", id: "vatican-city" },
        ],
      },
      {
        name: "North America",
        id: "north-america",
        regions: [
          {
            name: "Canada",
            id: "canada",
            subRegions: [
              { name: "Alberta", id: "alberta" },
              { name: "British Columbia", id: "british-columbia" },
              { name: "Manitoba", id: "manitoba" },
              { name: "New Brunswick", id: "new-brunswick" },
              { name: "Newfoundland and Labrador", id: "newfoundland-and-labrador" },
              { name: "Northwest Territories", id: "northwest-territories" },
              { name: "Nova Scotia", id: "nova-scotia" },
              { name: "Nunavut", id: "nunavut" },
              { name: "Ontario", id: "ontario" },
              { name: "Prince Edward Island", id: "prince-edward-island" },
              { name: "Quebec", id: "quebec" },
              { name: "Saskatchewan", id: "saskatchewan" },
              { name: "Yukon", id: "yukon" },
            ],
          },
          {
            name: "Mexico",
            id: "mexico",
            subRegions: [
              { name: "Aguascalientes", id: "aguascalientes" },
              { name: "Baja California", id: "baja-california" },
              { name: "Baja California Sur", id: "baja-california-sur" },
              { name: "Campeche", id: "campeche" },
              { name: "Chiapas", id: "chiapas" },
              { name: "Chihuahua", id: "chihuahua" },
              { name: "Ciudad de México", id: "ciudad-de-mexico" },
              { name: "Coahuila", id: "coahuila" },
              { name: "Colima", id: "colima" },
              { name: "Durango", id: "durango" },
              { name: "Guanajuato", id: "guanajuato" },
              { name: "Guerrero", id: "guerrero" },
              { name: "Hidalgo", id: "hidalgo" },
              { name: "Jalisco", id: "jalisco" },
              { name: "México", id: "mexico-state" },
              { name: "Michoacán", id: "michoacan" },
              { name: "Morelos", id: "morelos" },
              { name: "Nayarit", id: "nayarit" },
              { name: "Nuevo León", id: "nuevo-leon" },
              { name: "Oaxaca", id: "oaxaca" },
              { name: "Puebla", id: "puebla" },
              { name: "Querétaro", id: "queretaro" },
              { name: "Quintana Roo", id: "quintana-roo" },
              { name: "San Luis Potosí", id: "san-luis-potosi" },
              { name: "Sinaloa", id: "sinaloa" },
              { name: "Sonora", id: "sonora" },
              { name: "Tabasco", id: "tabasco" },
              { name: "Tamaulipas", id: "tamaulipas" },
              { name: "Tlaxcala", id: "tlaxcala" },
              { name: "Veracruz", id: "veracruz" },
              { name: "Yucatán", id: "yucatan" },
              { name: "Zacatecas", id: "zacatecas" },
            ],
          },
          {
            name: "United States",
            id: "usa",
            subRegions: [
              { name: "Alabama", id: "alabama" },
              { name: "Alaska", id: "alaska" },
              { name: "Arizona", id: "arizona" },
              { name: "Arkansas", id: "arkansas" },
              { name: "California", id: "california" },
              { name: "Colorado", id: "colorado" },
              { name: "Connecticut", id: "connecticut" },
              { name: "Delaware", id: "delaware" },
              { name: "Florida", id: "florida" },
              { name: "Georgia", id: "georgia-usa" },
              { name: "Hawaii", id: "hawaii" },
              { name: "Idaho", id: "idaho" },
              { name: "Illinois", id: "illinois" },
              { name: "Indiana", id: "indiana" },
              { name: "Iowa", id: "iowa" },
              { name: "Kansas", id: "kansas" },
              { name: "Kentucky", id: "kentucky" },
              { name: "Louisiana", id: "louisiana" },
              { name: "Maine", id: "maine" },
              { name: "Maryland", id: "maryland" },
              { name: "Massachusetts", id: "massachusetts" },
              { name: "Michigan", id: "michigan" },
              { name: "Minnesota", id: "minnesota" },
              { name: "Mississippi", id: "mississippi" },
              { name: "Missouri", id: "missouri" },
              { name: "Montana", id: "montana" },
              { name: "Nebraska", id: "nebraska" },
              { name: "Nevada", id: "nevada" },
              { name: "New Hampshire", id: "new-hampshire" },
              { name: "New Jersey", id: "new-jersey" },
              { name: "New Mexico", id: "new-mexico" },
              { name: "New York", id: "new-york" },
              { name: "North Carolina", id: "north-carolina" },
              { name: "North Dakota", id: "north-dakota" },
              { name: "Ohio", id: "ohio" },
              { name: "Oklahoma", id: "oklahoma" },
              { name: "Oregon", id: "oregon" },
              { name: "Pennsylvania", id: "pennsylvania" },
              { name: "Rhode Island", id: "rhode-island" },
              { name: "South Carolina", id: "south-carolina" },
              { name: "South Dakota", id: "south-dakota" },
              { name: "Tennessee", id: "tennessee" },
              { name: "Texas", id: "texas" },
              { name: "Utah", id: "utah" },
              { name: "Vermont", id: "vermont" },
              { name: "Virginia", id: "virginia" },
              { name: "Washington", id: "washington" },
              { name: "West Virginia", id: "west-virginia" },
              { name: "Wisconsin", id: "wisconsin" },
              { name: "Wyoming", id: "wyoming" },
              { name: "District of Columbia", id: "district-of-columbia" },
              { name: "Puerto Rico", id: "puerto-rico" },
            ],
          },
        ],
      },
      {
        name: "Oceania",
        id: "oceania",
        regions: [
          {
            name: "Australia",
            id: "australia",
            subRegions: [
              { name: "Australian Capital Territory", id: "australian-capital-territory" },
              { name: "New South Wales", id: "new-south-wales" },
              { name: "Northern Territory", id: "northern-territory" },
              { name: "Queensland", id: "queensland" },
              { name: "South Australia", id: "south-australia" },
              { name: "Tasmania", id: "tasmania" },
              { name: "Victoria", id: "victoria" },
              { name: "Western Australia", id: "western-australia" },
            ],
          },
          { name: "Fiji", id: "fiji" },
          { name: "Kiribati", id: "kiribati" },
          { name: "Marshall Islands", id: "marshall-islands" },
          { name: "Micronesia", id: "micronesia" },
          { name: "Nauru", id: "nauru" },
          {
            name: "New Zealand",
            id: "new-zealand",
            subRegions: [
              { name: "Auckland", id: "auckland" },
              { name: "Bay of Plenty", id: "bay-of-plenty" },
              { name: "Canterbury", id: "canterbury" },
              { name: "Gisborne", id: "gisborne" },
              { name: "Hawke's Bay", id: "hawkes-bay" },
              { name: "Manawatu-Wanganui", id: "manawatu-wanganui" },
              { name: "Marlborough", id: "marlborough" },
              { name: "Nelson", id: "nelson" },
              { name: "Northland", id: "northland" },
              { name: "Otago", id: "otago" },
              { name: "Southland", id: "southland" },
              { name: "Taranaki", id: "taranaki" },
              { name: "Tasman", id: "tasman" },
              { name: "Waikato", id: "waikato" },
              { name: "Wellington", id: "wellington" },
              { name: "West Coast", id: "west-coast" },
            ],
          },
          { name: "Palau", id: "palau" },
          { name: "Papua New Guinea", id: "papua-new-guinea" },
          { name: "Samoa", id: "samoa" },
          { name: "Solomon Islands", id: "solomon-islands" },
          { name: "Tonga", id: "tonga" },
          { name: "Tuvalu", id: "tuvalu" },
          { name: "Vanuatu", id: "vanuatu" },
        ],
      },
      {
        name: "South America",
        id: "south-america",
        regions: [
          {
            name: "Argentina",
            id: "argentina",
            subRegions: [
              { name: "Buenos Aires", id: "buenos-aires" },
              { name: "Catamarca", id: "catamarca" },
              { name: "Chaco", id: "chaco" },
              { name: "Chubut", id: "chubut" },
              { name: "Córdoba", id: "cordoba" },
              { name: "Corrientes", id: "corrientes" },
              { name: "Entre Ríos", id: "entre-rios" },
              { name: "Formosa", id: "formosa" },
              { name: "Jujuy", id: "jujuy" },
              { name: "La Pampa", id: "la-pampa" },
              { name: "La Rioja", id: "la-rioja" },
              { name: "Mendoza", id: "mendoza" },
              { name: "Misiones", id: "misiones" },
              { name: "Neuquén", id: "neuquen" },
              { name: "Río Negro", id: "rio-negro" },
              { name: "Salta", id: "salta" },
              { name: "San Juan", id: "san-juan" },
              { name: "San Luis", id: "san-luis" },
              { name: "Santa Cruz", id: "santa-cruz" },
              { name: "Santa Fe", id: "santa-fe" },
              { name: "Santiago del Estero", id: "santiago-del-estero" },
              { name: "Tierra del Fuego", id: "tierra-del-fuego" },
              { name: "Tucumán", id: "tucuman" },
            ],
          },
          { name: "Bolivia", id: "bolivia" },
          {
            name: "Brazil",
            id: "brazil",
            subRegions: [
              { name: "Acre", id: "acre" },
              { name: "Alagoas", id: "alagoas" },
              { name: "Amapá", id: "amapa" },
              { name: "Amazonas", id: "amazonas" },
              { name: "Bahia", id: "bahia" },
              { name: "Ceará", id: "ceara" },
              { name: "Distrito Federal", id: "distrito-federal" },
              { name: "Espírito Santo", id: "espirito-santo" },
              { name: "Goiás", id: "goias" },
              { name: "Maranhão", id: "maranhao" },
              { name: "Mato Grosso", id: "mato-grosso" },
              { name: "Mato Grosso do Sul", id: "mato-grosso-do-sul" },
              { name: "Minas Gerais", id: "minas-gerais" },
              { name: "Pará", id: "para" },
              { name: "Paraíba", id: "paraiba" },
              { name: "Paraná", id: "parana" },
              { name: "Pernambuco", id: "pernambuco" },
              { name: "Piauí", id: "piaui" },
              { name: "Rio de Janeiro", id: "rio-de-janeiro" },
              { name: "Rio Grande do Norte", id: "rio-grande-do-norte" },
              { name: "Rio Grande do Sul", id: "rio-grande-do-sul" },
              { name: "Rondônia", id: "rondonia" },
              { name: "Roraima", id: "roraima" },
              { name: "Santa Catarina", id: "santa-catarina" },
              { name: "São Paulo", id: "sao-paulo" },
              { name: "Sergipe", id: "sergipe" },
              { name: "Tocantins", id: "tocantins" },
            ],
          },
          {
            name: "Chile",
            id: "chile",
            subRegions: [
              { name: "Arica y Parinacota", id: "arica-y-parinacota" },
              { name: "Tarapacá", id: "tarapaca" },
              { name: "Antofagasta", id: "antofagasta" },
              { name: "Atacama", id: "atacama" },
              { name: "Coquimbo", id: "coquimbo" },
              { name: "Valparaíso", id: "valparaiso" },
              { name: "Santiago Metropolitan", id: "santiago-metropolitan" },
              { name: "O'Higgins", id: "ohiggins" },
              { name: "Maule", id: "maule" },
              { name: "Ñuble", id: "nuble" },
              { name: "Biobío", id: "biobio" },
              { name: "Araucanía", id: "araucania" },
              { name: "Los Ríos", id: "los-rios" },
              { name: "Los Lagos", id: "los-lagos" },
              { name: "Aysén", id: "aysen" },
              { name: "Magallanes", id: "magallanes" },
            ],
          },
          { name: "Colombia", id: "colombia" },
          { name: "Ecuador", id: "ecuador" },
          { name: "Guyana", id: "guyana" },
          { name: "Paraguay", id: "paraguay" },
          { name: "Peru", id: "peru" },
          { name: "Suriname", id: "suriname" },
          { name: "Uruguay", id: "uruguay" },
          { name: "Venezuela", id: "venezuela" },
        ],
      },
    ],
  }
}
